# Generated by Django 5.1.6 on 2025-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("medecin", "Médecin"),
                    ("pharmacien", "Pharmacien"),
                    ("patient", "Patient"),
                    ("superadmin", "Super Admin"),
                    ("ministere", "Ministère"),
                    ("services", "Services"),
                ],
                default="patient",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
