# Generated by Django 5.1.6 on 2025-03-11 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultation", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantite_stock", models.PositiveIntegerField(default=0)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PNDS", "Médicament issu du PNDS"),
                            ("COMMUN", "Médicament général"),
                        ],
                        default="COMMUN",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SatisfactionOrdonnance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("En attente", "En attente"), ("Validée", "Validée")],
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satisfactions",
                        to="consultation.ordonnance",
                    ),
                ),
                (
                    "pharmacien",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pharmacien",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockMouvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="Quantité")),
                (
                    "date_mouvement",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date du mouvement"
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("Entrée", "Entrée"), ("Sortie", "Sortie")],
                        max_length=50,
                        verbose_name="Type de mouvement",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacie.medicament",
                        verbose_name="Médicament",
                    ),
                ),
            ],
        ),
    ]
