# Generated by Django 5.1.6 on 2025-03-11 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_management', '0002_alter_customuser_options_alter_customuser_groups_and_more'),
        ('auth', '0013_auto_20250309_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='access_management_customuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='access_management.role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='access_management_customuser_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('medecin', 'Médecin'), ('patient', 'Patient'), ('pharmacien', 'Pharmacien'), ('ministere', 'Ministère'), ('personnel_admin', 'Personnel Administratif'), ('bureau_entree', 'Bureau Entrée'), ('services', 'Services')], max_length=50, unique=True),
        ),
    ]
