# Generated by Django 5.1.6 on 2025-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyseMedicale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_analyse", models.CharField(max_length=255)),
                ("resultat", models.TextField(blank=True, null=True)),
                ("date_analyse", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hopital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_hopital", models.CharField(max_length=255)),
                ("adresse_hopital", models.TextField()),
                ("categorie", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("capacity", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Laboratoire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du laboratoire"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("dentaire", "Cabinet Dentaire"),
                            ("gynecologie", "Gynécologie"),
                            ("dermatologie", "Dermatologie"),
                            ("soins_intensifs", "Soins Intensifs"),
                            ("pediatrie", "Pédiatrie"),
                            ("autre", "Autre"),
                        ],
                        max_length=255,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
